### ISSUE TITLE
Script Broken After Newest Blueprint Installation Release

### ISSUE THREAD

**Issue by sebshaffer** [Red-print/Redprint#4]
The script calls to the Blueprint API and seems to never be able to reach it and load indefinitely. The script will then continue to run and never complete the install.

**Comment by growtoups** [comment]
Alright im going to look into it thanks for pointing it out sorry for taking so long to see your issue

**Comment by growtoups** [comment]
I asked Ivy (purple) about if he changed anything and he said that he didnt and it could be the fact that he had some upstream downtime which would explain the issue anyway i'll close the issue for now.
