### ISSUE TITLE
When updating using redprint, it installs an outdated version

### ISSUE THREAD

**Issue by SuperEvilLuke** [Red-print/Redprint#5]
When I updated pterodactly and blueprint with redprint it installed an outdated version of pterodactyl 
![image](https://github.com/Red-print/Redprint/assets/97245327/6b8c2c3f-0c35-41c3-8004-46481bca86c1)

**Comment by growtoups** [comment]
blueprint is responsible for updating the file that visually displays the Pterodactyl panel version. Please note that these changes are purely visual, and the actual version remains 1.11.7. The team is currently working on a fix for this issue. We (Redprint) are not at fault for this error.
